### ISSUE TITLE
accuracy mismatch

### ISSUE THREAD

**Issue by woo1** [ivadym/FER#1]
Thanks for sharing your code.

I tried training with your code and data.
(src/ResNet-50.ipynb, FER-2013/fer_2013_train.csv)
I changed the batch size to 64 because of memory error.
And other codes are same.
But the accuracy is much lower than your model.
Your model(ResNet-50)'s accuracy is 71.25% but my models' is 17.44%.
Do I need to add another code for training?

"""
Accuracy:
0.1744218445249373

Report:
                     precision    recall  f1-score   support

       Anger           0.00      0.00      0.00       491
     Disgust           0.00      0.00      0.00        55
        Fear            0.00      0.00      0.00       528
  Happinness       0.00      0.00      0.00       879
     Sadness         0.00      0.00      0.00       594
    Surprise           0.00      0.00      0.00       416
     Neutral            0.17      1.00      0.30       626

    accuracy                                    0.17      3589
   macro avg        0.02      0.14      0.04      3589
weighted avg       0.03      0.17      0.05      3589
"""

**Comment by ivadym** [comment]
The non-correlation with my results may be because you do not preprocess the images when you verify the model. That is, the preprocessing of the images to be trained should be the same when you check the effectiveness of the model.

I can not think of anything else.

I'm sorry I didn't answer you before but I hope it helps someone.

Good luck!

**Comment by haonguyen1107** [comment]
Thanks for sharing your code.
I try to resize image in colab but have an error:Your session crashed after using all available RAM.I am not getting why it crashes only on it.

**Comment by ivadym** [comment]
I'm not sure what caused your problem, but chances are you have exceeded the memory limit, especially if you are using larger images. Try a smaller dataset or increase the size of the RAM.

On the other hand, you can always check the logs to see what has really happened.

**Comment by radhikachoudhary64** [comment]
Hey i am running this on aws . I running resnet50.ipynb model but i m getting 
TypeError: raise: exception class must be a subclass of BaseException.
Can you help me fix it ?

**Comment by mrityu-jha** [comment]
Hey

In resnet50.ipynb you have given img_height and img_width to be 197 but in `get_data( dataset)` function you have commented that dimension is being resized to 139 x 139 x 3. Is it by mistake or I am missing out on something?

**Comment by ivadym** [comment]
Hi,

It's a mistake. The images are being resized to 197x197 in the ResNet-50 and to 139x139 in the Inceptio-v3 & ResNet-v2 models.

Good luck with your project!

**Comment by ivadym** [comment]
> Hey
> 
> In resnet50.ipynb you have given img_height and img_width to be 197 but in `get_data( dataset)` function you have commented that dimension is being resized to 139 x 139 x 3. Is it by mistake or I am missing out on something?

Hi,

It's a mistake. The images are being resized to 197x197 in the ResNet-50 and to 139x139 in the Inceptio-v3 & ResNet-v2 models.

Good luck with your project!
